[build]
  # กำหนดโฟลเดอร์ที่จะเผยแพร่ (ในที่นี้คือ root)
  publish = "."
  # ไม่ต้องมีคำสั่ง build เพราะเป็น static HTML/CSS/JS
  command = ""

[dev]
  # สำหรับการรัน netlify dev
  command = "node server.js"
  port = 3000
